### ISSUE TITLE
Unauthorized while requesting access token using php

### ISSUE THREAD

**Issue by Dhavalptel** [BioID-GmbH/BWS-GUI#1]
Hi guys please let me know how to get access token in PHP here is below code, I have used guzzle HTTP library for requesting the access token
```
$uriBase = 'https://bws.bioid.com/extension/token';

        //set the request params
        $requestParameters = [
            'id' => env('BIOID_APP_ID'),
            'bcid' => env('BIOID_BCID'),
            'task'=>'verify',
            'autoenroll'=>'False',
            'livedetection'=>'True',
            'challenge'=>'False',
            'maxtries'=>10,
            'traits'=>'Face,Periocular'
        ];

        //set the headers
        $requestHeaders=[
            'Authorization'=>'Basic'.base64_encode(env('BIOID_APP_ID').":". env('BIOID_CLIENT_SECRET'))
        ];
        //send the request to BIOID server and return the response
        $response = $this->client->get($uriBase,[
            'query'=>$requestParameters,
            'headers' =>$requestHeaders,
        ]);
        return json_encode(json_decode($response->getBody()->getContents()), JSON_PRETTY_PRINT);
```
but I am getting 
``` 401 Unauthorized response: {"Message":"Unauthorized"}```

**Comment by Dhavalptel** [comment]
Thanks, I got it using `https://account.bioid.com/connect/token` Closing this

**Comment by CmdQ** [comment]
Great. But also, it seems you miss a space after your "Basic" before appending the base64-encoded stuff.

**Comment by Dhavalptel** [comment]
@CmdQ  But accessing with `https://account.bioid.com/connect/token` does not require basic authentication
```
$uriBase = 'https://account.bioid.com/connect/token';
        //set the request header
        $requestHeaders=[
            'Content-Type' => 'application/x-www-form-urlencoded',
        ];
        //set the body params
        $requestParams=[
            'client_id'=>env('BIOID_CLIENT_ID'),
            'grant_type'=>'client_credentials',
            'client_secret'=>env('BIOID_CLIENT_SECRET')
        ];
        //send the request to BIOID server and return the response
        $response = $this->client->post($uriBase,[
            'headers'=>$requestHeaders,
            'form_params' =>$requestParams,
        ]);
        return json_encode(json_decode($response->getBody()->getContents()), JSON_PRETTY_PRINT);
```

**Comment by Dhavalptel** [comment]
Though, I am also having the issue with `Upload API`  with the following error
"Message":"The API call requires authentication. Try to request a Web Token before calling this method."
```
        $uriBase = 'https://bws.bioid.com/extension/upload';
        $imageUrl = 'https://upload.wikimedia.org/wikipedia/commons/3/37/Dagestani_man_and_woman.jpg';

        //send the request to BIOID server and return the response
        $response = $this->client->post($uriBase,[
            'query'=>['tag'=>'up'],
            'headers'=>['Authorization' => 'Bearer '. $request->token],
            'form_params'=>['image' =>base64_encode($imageUrl)]
        ]);
        return json_encode(json_decode($response->getBody()->getContents()), JSON_PRETTY_PRINT);
```

**Comment by CmdQ** [comment]
Disclaimer: I don't know much about PHP and cannot try your samples.

What I see:
- Yes, the token call *does need* basic auth.
- Why do you use `application/x-www-form-urlencoded`? It is not understood by the token call. Only a few of our calls understand that one.
- Where do you get the parameter names `client_id`, `grant_type` and `client_secret` from?

See the [token documentation][token] about the two mandatory parameters (**all via GET!**) and authorization. Also you can find a sample response. Check that yours looks similar.

Your [first try](#issue-352228776) was much better, you [just forgot the space  between “Basic” and the base64-encoded string](#issuecomment-414907253).

[token]: https://developer.bioid.com/bwsreference/web-api/web-token-api

**Comment by Dhavalptel** [comment]
@CmdQ Thanks for the reply, I have added space between basic and base64-encoded string but still, it's throwing ```"Message":"Unauthorized"```

**Comment by Dhavalptel** [comment]
@CmdQ  Though I was trying to access status [https://developer.bioid.com/bwsreference/web-api/web-status-api] but still that is throwing `Unauthorized`

**Comment by CmdQ** [comment]
At the moment I can only tell you to double-check the spelling/casing of your app id and secret. I just tried changing a tiny bit and got to the same error message as you.

Maybe try [status](https://developer.bioid.com/bwsreference/web-api/web-status-api) first. It does not need any parameters, so one less thing to go wrong. Authorization is the same.

**Comment by CmdQ** [comment]
Oh, now I see something else: you [tried](#issuecomment-414675947) to get the token from <https://account.bioid.com/connect/token>. That is **our** user management and that token is of no use to you.

If you want to call 

    https://bws.bioid.com/extension/upload

then you need to get your token at

    https://bws.bioid.com/extension/token

Same prefix for all calls!

Again, your first try was the most correct.

**Comment by Dhavalptel** [comment]
Okay, I am closing this issue now I am able to get status, token 
Thanks for the help
