### ISSUE TITLE
Unauthorized while requesting access token using aspnet on starting the solution

### ISSUE THREAD

**Issue by prernad0903** [BioID-GmbH/BWS-GUI#2]
I am trying to execute the aspnet solution provided, but am getting the below error - 

![image](https://user-images.githubusercontent.com/42011233/73186420-b09f4c00-4145-11ea-99c8-0fdc76269e47.png)

Have changed the app id and app secret in the solution, HomeController.cs file, as mentioned but getting the above error

Please advise.
Thanks in advance

**Comment by mebealex** [comment]
Are you sure you are using the correct credentials?

To successfully run one of the sample web apps, you need to have access to an existing BWS installation. If you don't have this access you can register for a BWS trial instance here:
https://bwsportal.bioid.com/register - requires login.

**Comment by prernad0903** [comment]
I have registered for a trial instance,and have also created a client application using the account portal. 
Added the client ID and secret key generated in the HomeController.cs file but still was getting the error.

Changed the app id and secret key to the one used in BioID playground, but still getting the same error.

Also, are the app id and client id same?Are there any other configurations needed?

**Comment by mebealex** [comment]
I think you have registered a BioID Connect client application.

For this GitHub sample you need the Web API key from BwsPortal.

Please visit the BwsPortal https://bwsportal.bioid.com again and 
register for BWS trial instance. After activation you can go to the 
configuration section and create a new Web API key for this GitHub sample.

**Comment by prernad0903** [comment]
Thanks, it was the Web API key that was missing. I am able to test the application
